### ISSUE TITLE
Project Testing/Enhancement Request

### ISSUE THREAD

**Issue by jtstanczak7** [cis3296f23/Orthography-Overlord#117]
Following the canvas announcement about project testing, I tested your project and there does not seem to be any issues or bugs when playing. The application is very easy to understand and I had no issues downloading and running.

Instead of reporting an issue, one of the enhancement requests I have is to shuffle the words presented to the user. I am not sure if this is part of future plans, but I think it will make replaying more fun, or if you're using this to study, more effective. Another enhancement request that would appeal to some users would be allowing the user to change the difficulty of words. What makes a word difficult can be subjective, but I think it would be cool.

I like that the words the user spells incorrectly reappear, and I am a fan of the background image.

Overall, the application looks great, and I am excited to see the end product!

**Comment by gummyfrog** [comment]
Thanks for the feedback!
