### ISSUE TITLE
Update project proposal to change all Python related information to ElectronJS

### ISSUE THREAD

**Issue by mustafamalik-tu** [cis3296f23/Orthography-Overlord#16]
[Malik, Mustafa-Project_Proposal.docx](https://github.com/cis3296f23/Orthography-Overlord/files/13300552/Malik.Mustafa-Project_Proposal.docx)

**Comment by gummyfrog** [comment]
[Malik-Mustafa-No-Python.docx](https://github.com/cis3296f23/Orthography-Overlord/files/13311154/Malik-Mustafa-No-Python.docx)
