### ISSUE TITLE
FOUR User Personas

### ISSUE THREAD

**Issue by gummyfrog** [cis3296f23/Orthography-Overlord#3]

**Comment by mustafamalik-tu** [comment]
Everyone needs to create one User Persona. Please write in discord what user persona you will be making so that we all have different personas with different needs and desires from the application.

**Comment by gummyfrog** [comment]
**Mustafa's Persona: Little Timmy**
5th grade student that wants to improve his spelling! Plays mobile games sometimes but doesn't play any desktop games. Doesn't care about how fast he can type words, he just wants to spell accurately.

**Neil's Persona: Lauren Ipsum**
Lauren is a teenage pop-star from Korea. 
She has a high school diploma and she considers herself a fluent English reader.
She wants to perform in America, but she's worried about her English fluency. She hasn't had many opportunities to hear English words spoken out loud!


**Alex's Persona: Johnny Cash**
Johnny is a southern man. He dropped out of highschool in grade 12 to help his father on the family farm and wasn't exactly a good student to begin with. He has no time for technology, especially not video games, but Johnny's daughter Bethany has played many games to help improve her vocabulary. Bethany has been struggling in her studies recently, and Johnny has felt helpless to assist her in doing her homework. He has set out to improve his vocabulary so he can help his daughter with her English assignments.

**Comment by gummyfrog** [comment]
Once @tuk05348 submits a user persona, I'll create a little PDF collecting them all.

**Comment by gummyfrog** [comment]
## Niaz's Persona: Bill Lumbergh

Bill is a middle manager in Texas. He once had a promising career before him, graduating from MIT with a B.S. in Physics. However instead of pursuing a career in the sciences he was drawn to the dot-com bubble and joined various software companies, working his way up from junior developer to project manager, and ultimately becoming a Division Vice President for Initech, a software company based in Texas. After becoming a manager Bill slowly lost any programming skills he had, along with any of the scientific knowledge he once knew. While he can generally navigate a user interface he is overall a novice user and is prone to criticizing a system for minor faults.

As a part of middle management he revels in tormenting his subordinates by nitpicking minor mistakes and punishing ones he does not like with menial tasks. He wants to use Orthography Overlord to improve his vocabulary and further expand his efforts in nitpicking. For example, by chastising subordinates for not using a more complex and obscure word in a TPS report and if they protest he wants to further demean them by implying they are not smart enough to spell it or use it.
